import type { McpDirectoryInfo } from "@/app/constants";

export const LOCAL_MCP_QUICK_CONNECT = Object.freeze([
  {
    name: "Notion",
    serverName: "notion",
    description: "Connect a user-authorized Notion workspace.",
    url: "https://mcp.notion.com/mcp",
    type: "remote",
    oauth: true,
    kind: "mcp",
    iconSrc: "/ext-notion.svg",
  },
  {
    name: "Linear",
    serverName: "linear",
    description: "Connect a user-authorized Linear workspace.",
    url: "https://mcp.linear.app/mcp",
    type: "remote",
    oauth: true,
    kind: "mcp",
    iconSrc: "/ext-linear.svg",
  },
  {
    name: "Sentry",
    serverName: "sentry",
    description: "Connect a user-authorized Sentry account.",
    url: "https://mcp.sentry.dev/mcp",
    type: "remote",
    oauth: true,
    kind: "mcp",
    iconSrc: "/ext-sentry.svg",
  },
  {
    name: "Stripe",
    serverName: "stripe",
    description: "Connect a user-authorized Stripe account.",
    url: "https://mcp.stripe.com",
    type: "remote",
    oauth: true,
    kind: "mcp",
    iconSrc: "/ext-stripe.svg",
  },
  {
    name: "Context7",
    serverName: "context7",
    description: "Use current library documentation through Context7.",
    url: "https://mcp.context7.com/mcp",
    type: "remote",
    oauth: false,
    kind: "mcp",
    iconSrc: "/ext-context7.svg",
  },
] satisfies McpDirectoryInfo[]);
